config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :characteristics
  resources :features
  resources :ministers
  resources :places do
    resources :parishioners
  end
  resources :parishioners do
    resources :visits
  end
  resources :streets
  resources :visits
  root "streets#index"
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
    belongs_to :user
    has_many :characteristics_parishioners
    has_many :parishioners, through: :characteristics_parishioners, :dependent => :destroy
    default_scope { order(archive: :asc, name: :asc) }
    validates :name, :presence => true
end

app/models/feature.rb
class Feature < ApplicationRecord
    belongs_to :user
    has_many :features_places
    has_many :places, through: :features_places, :dependent => :destroy
    default_scope { order(name: :desc) }
    validates :name, :presence => true
end

app/models/features_place.rb
class FeaturesPlace < ApplicationRecord
  belongs_to :feature
  belongs_to :place
end

app/models/minister.rb
class Minister < ApplicationRecord
    belongs_to :user
    default_scope { order(fullname: :asc) }
    validates :fullname, :presence => true
    has_many :visits, dependent: :destroy
end

app/models/parishioner.rb
class Parishioner < ApplicationRecord
  belongs_to :place
  belongs_to :user
  has_many :visits, dependent: :destroy
  accepts_nested_attributes_for :visits
  has_many :characteristics_parishioners
  has_many :characteristics, through: :characteristics_parishioners, :dependent => :destroy
  default_scope { order(lastname: :asc, firstname: :asc) }
  validates :firstname, :lastname, :birth, :place_id, :presence => true
  def fullname
    "#{firstname} #{lastname}"
  end
  def self.ransackable_associations(auth_object = nil)
    ["characteristics", "characteristics_parishioners", "place", "user", "visits"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["archive", "baptism_date", "baptism_number", "baptism_parish", "birth", "birth_place", "confirmation_date", "confirmation_name", "confirmation_number", "confirmation_witness", "created_at", "death_date", "death_mark", "email", "firstname", "id", "lastname", "notes", "phone", "place_id", "updated_at", "user_id"]
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :street
  belongs_to :user
  before_save :change_numbers
  has_many :parishioners, dependent: :destroy
  accepts_nested_attributes_for :parishioners
  has_many :features_places
  has_many :features, through: :features_places, :dependent => :destroy
  validates :address, :street_id, :presence => true
  default_scope { joins(:street).merge(Street.order(name: :asc, address: :asc)).all }
  def next
    Place.where("street_id = ? AND address > ?", self.street.id, address).first || Place.where("street_id = ?", self.street.id).first
  end
  def prev
    Place.where("street_id = ? AND address < ?", self.street.id, address).last || Place.where("street_id = ?", self.street.id).last
  end
  def full_address
    "#{street.name} #{address}"
  end
  def self.ransackable_attributes(auth_object = nil)
    ["address", "archive", "created_at", "id", "notes", "street_id", "updated_at", "user_id"]
  end
  def change_numbers
    address.gsub!(/\b([0-9])\b/, '00\1')
    address.gsub!(/\b([0-9]{2})\b/, '0\1')
  end
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :user
  self.per_page = 100
  before_save :change_numbers
  default_scope { order(name: :asc) }
  validates :name, :presence => true
  has_many :places, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["archive", "created_at", "id", "name", "notes", "updated_at", "user_id"]
  end
  def change_numbers
    name.gsub!(/\b([0-9])\b/, '00\1')
    name.gsub!(/\b([0-9]{2})\b/, '0\1')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :presence => true
  has_secure_password
  has_many :places, dependent: :destroy
  has_many :streets, dependent: :destroy
  has_many :characteristics, dependent: :destroy
  has_many :features, dependent: :destroy
  has_many :ministers, dependent: :destroy
  has_many :visits, dependent: :destroy
  has_many :parishioners, dependent: :destroy
  accepts_nested_attributes_for :parishioners
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  self.per_page = 250
  belongs_to :parishioner
  belongs_to :minister
  default_scope { order(issue: :desc) }
  validates :parishioner_id, :minister_id, :issue, :presence => true
  def self.ransackable_attributes(auth_object = nil)
    ["anointing", "confession", "created_at", "eucharist", "id", "issue", "minister_id", "notes", "parishioner_id", "updated_at", "user_id"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["minister", "parishioner", "user"]
  end
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :authorize
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  def index
    @characteristics = current_user.characteristics
  end

  def show
  end

  def new
    @characteristic = current_user.characteristics.build
  end

  def edit
  end

  def create
    @characteristic = current_user.characteristics.build(characteristic_params)

    if @characteristic.save
      redirect_to @characteristic, notice: 'Grupa została utworzona.'
    else
      render :new
    end
  end

  def update
    if @characteristic.update(characteristic_params)
      redirect_to @characteristic, notice: 'Grupa została zaktualizowana.'
    else
      render :edit
    end
  end

  def destroy
    @characteristic.destroy
    redirect_to characteristics_url, notice: 'Grupa została usunięta.'
  end

  private
    def set_characteristic
      @characteristic = current_user.characteristics.find(params[:id])
    end

    def characteristic_params
      params.require(:characteristic).permit(:name, :notes, :archive)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authorize
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.places.includes(:street).ransack(params[:q])
    @places = @q.result.paginate(page: params[:page])
    @streets = current_user.streets
    @features = current_user.features
    @stats= @q.result(distinct: true)
  end

  def show
    @parishioner = current_user.parishioners.build
    @parishioner.place_id = @place.id
    @place.parishioners.build
  end

  def new
    @place = current_user.places.build
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)

    if @place.save
      redirect_to @place, notice: 'Adres został dodany.'
    else
      render :new
    end
  end

  def update
    if @place.update(place_params)
      redirect_to @place, notice: 'Adres został zaktualizowany.'
    else
      render :edit
    end
  end

  def destroy
    @place.destroy
    redirect_to places_url, notice: 'Adres i powiązane z nim dane zostały usuniete.'
  end

  private

    def set_place
      @place = current_user.places.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:street_id, :address, :notes, :archive, :feature_ids=>[], parishioners_attributes: [:id, :place_id, :firstname, :lastname, :birth, :user_id, :_destroy, :characteristic_ids=>[]])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to root_url, notice: 'Baza została utworzona!'
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:email, :password)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/ministers_helper.rb
module MinistersHelper
end

app/helpers/parishioners_helper.rb
module ParishionersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/characteristics/_form.html.haml
= bootstrap_form_for @characteristic do |f|
  - if characteristic.errors.any?
    #error_explanation
      %b.text-primary
        = pluralize(characteristic.errors.count, "")
        do poprawienia!

  .field
    = f.text_field :name, label: "Nazwa grupy"
  .field
    = f.text_area :notes, label: "Notatki"
  .field
    = f.check_box :archive, label: "Archiwum"
  .actions
    = f.submit 'Wyślij', class: "btn btn-primary float-right mb-4"

app/views/characteristics/_item.html.haml
%h5.no-print
  = link_to 'Grupy', characteristics_path
  |
  = @characteristic.name
%b#notice.text-primary.no-print= notice
.no-print= render 'form', characteristic: @characteristic
%br
%br
%h5= @characteristic.name
= characteristic.parishioners.count
osób w tej grupie.
%p= @characteristic.notes
- if @characteristic.parishioners.present?
  - if @characteristic.name.include? "#"
    Użycie # w nazwie ukrywa listę parafian i blokuje usunięcie.
  - else 
    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            - if @characteristic.name.include? "Bierzmowani"
              %th Nr
            %th Nazwisko i imię
            - if @characteristic.name.include? "Bierzmowani"
              %th Patron
              %th Data i miejsce ur.
              %th Świadek
              %th Nr aktu chrztu
              %th Parafia chrztu
              %th Notatki
            - if @characteristic.name.include? "Chorzy"
              %th Ostatnia wizyta
              %th Notatki
        %tbody
          - @characteristic.parishioners.reorder(lastname: :asc, firstname: :asc).each do |parishioner|
            %tr{style: "page-break-inside: avoid; page-break-after: auto;"}
              - if @characteristic.name.include? "Bierzmowani"
                %td
                  = parishioner.confirmation_number
              %td
                - if parishioner.death_mark == true 
                  = parishioner.death_mark ? "✝️".html_safe : " ".html_safe
                - else
                  = parishioner.archive ? "📁".html_safe : " ".html_safe
                %b= link_to parishioner.fullname, parishioner, class: 'text-primary'
                %i= parishioner.notes
                = parishioner.phone
                = parishioner.email
                %br
                - if @characteristic.name.include? "Bierzmowani" 
                - elsif @characteristic.name.include? "Chorzy"
                  - if parishioner.death_mark == true 
                    - if parishioner.birth.present?
                      = parishioner.birth.strftime("ur. %d-%m-%Y")
                    
                    - if parishioner.death_date.present?
                      = parishioner.death_date.strftime("zm. %d-%m-%Y")
                      w wieku
                      %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor - ((Time.zone.now - parishioner.death_date.to_time) / 1.year.seconds).floor
                      lat
                      
                  - else
                    - if parishioner.birth.present?
                      lat 
                      %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor
                      = parishioner.birth.strftime("ur. %d-%m-%Y")
                  %p= link_to parishioner.place.full_address, parishioner.place
                  
                - else
                  = link_to parishioner.place.full_address, parishioner.place



              - if @characteristic.name.include? "Bierzmowani"
                %td
                  = parishioner.confirmation_name
                %td
                  = parishioner.birth
                  = parishioner.birth_place
                %td
                  = parishioner.confirmation_witness
                %td
                  = parishioner.baptism_number
                %td
                  = parishioner.baptism_parish
                %td
                  = parishioner.notes
                  %br
                  = parishioner.phone
                  %br
                  = parishioner.email

              - if @characteristic.name.include? "Chorzy"
                %td
                  - parishioner.visits.limit(1).each do |visit|
                    - if visit.issue.present?
                      = link_to visit.issue.strftime("%d-%m-%Y"), edit_visit_path(visit)
                    %br
                    - if visit.eucharist  == true 
                      .badge.badge-primary.text-white.mb-2 Komunia
                    - if visit.confession  == true 
                      .badge.badge-primary.text-white.mb-2 Spowiedź
                    - if visit.anointing  == true 
                      .badge.badge-primary.text-white.mb-2 Namaszczenie
                    %i= visit.notes
                    %br
                    %b
                      - if visit.minister.present?
                        = visit.minister.fullname
                %td
                  = parishioner.notes
                  %br
                  = parishioner.phone
                  %br
                  = parishioner.email

- if @characteristic.name.include? "#"
- else
  .no-print          
    %button.btn.btn-outline-dark{"aria-controls" => "confirmation-collapse", "aria-expanded" => "false", "data-target" => "#confirmation-collapse", "data-toggle" => "collapse", :type => "button"}
      Usuń grupę!
    #confirmation-collapse.collapse
      
      %p.text-primary.mt-2 Ta operacja nie jest odwracalna!     
      
      = link_to "Usuń grupę!", @characteristic, title: 'Usuń', class: 'btn btn-dark float-left', method: :delete, data: { confirm: 'Czy chcesz usunąć tę grupę?', remote: true }

app/views/characteristics/edit.html.haml
= render 'item', characteristic: @characteristic

app/views/characteristics/index.html.haml
= link_to '+ Nowa grupa', new_characteristic_path, class: "btn btn-primary float-right mb-2"
%h5 
  = link_to 'Parafianie', parishioners_path
  |
  Grupy
%b#notice.text-primary= notice
%table.table.table-striped.table-bordered.table-hover.mb-4.py-4
  %tbody
    - @characteristics.reorder(archive: :asc, name: :asc).each do |characteristic|
      %tr
        %td!
          = characteristic.archive ? "📁".html_safe : " ".html_safe
          = link_to characteristic.name, characteristic
        %td
          = characteristic.parishioners.count
        %td= characteristic.notes
%br

app/views/characteristics/new.html.haml
%h5 
  = link_to 'Grupy', characteristics_path
  | Nowa grupa
= render 'form', characteristic: @characteristic

app/views/characteristics/show.html.haml
= render 'item', characteristic: @characteristic