config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :characteristics
  resources :features
  resources :ministers
  resources :places do
    resources :parishioners
  end
  resources :parishioners do
    resources :visits
  end
  resources :streets
  resources :visits
  root "streets#index"
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  self.per_page = 250
  belongs_to :parishioner
  belongs_to :minister
  default_scope { order(issue: :desc) }
  validates :parishioner_id, :minister_id, :issue, :presence => true
  def self.ransackable_attributes(auth_object = nil)
    ["anointing", "confession", "created_at", "eucharist", "id", "issue", "minister_id", "notes", "parishioner_id", "updated_at", "user_id"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["minister", "parishioner", "user"]
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :authorize
  before_action :set_visit, only: [:show, :edit, :update]

  def index
    @q = current_user.visits.includes(:parishioner).includes(:minister).ransack(params[:q])
    @visits = @q.result.paginate(page: params[:page])
  end

  def show
  end

  def new
    @visit = current_user.visits.build
  end

  def edit
  end

  def create
    @parishioner = current_user.parishioners.find(params[:parishioner_id])
    @visit = @parishioner.visits.create(visit_params)
    redirect_to @parishioner
  end

  def update
    if @visit.update(visit_params)
      redirect_to @visit, notice: 'Wizyta została zaktualizowana.'
    else
      render :edit
    end
  end

  def destroy
    @parishioner = current_user.parishioners.find(params[:parishioner_id])
    @visit = @parishioner.visits.find(params[:id])
    @visit.destroy
    redirect_to parishioner_path(@parishioner), notice: 'Wizyta została usunięta.'
  end

  private
    def set_visit
      @visit = current_user.visits.find(params[:id])
    end

    def visit_params
      params.require(:visit).permit(:issue, :parishioner_id, :minister_id, :eucharist, :confession, :anointing, :notes, :user_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.haml
= bootstrap_form_with(model: visit) do |form|
  - if visit.errors.any?
    #error_explanation
      %b.text-primary
        = pluralize(visit.errors.count, "")
        do poprawienia!
  .field
    = form.date_field :issue, label: "Data wizyty"
  .field
    = form.check_box :eucharist, label: "Komunia"
  .field
    = form.check_box :confession, label: "Spowiedź"
  .field
    = form.check_box :anointing, label: "Namaszczenie"
  .field
    = form.text_area :notes, label: "Notatki"
  .field
    = form.collection_select(:minister_id, current_user.ministers, :id, :fullname, {label: 'Szafarz'}, { class: "selectpicker", data: { live_search: 'true' } })
    = form.hidden_field :user_id, :value => @current_user.id
  .actions.mt-4
    = form.submit "Aktualizuj", class: "btn btn-primary float-right mb-4"
%br
%br
%br

app/views/visits/_item.html.haml
%h5
  = link_to 'Parafianie', parishioners_path
  |
  = link_to 'Wizyty', visits_path
  |
  = link_to @visit.parishioner.fullname, @visit.parishioner
%b#notice.text-primary= notice
= render 'form', visit: @visit
%br
%br

app/views/visits/_visit.html.haml
.card.text-white.bg-primary
  .card-header
    Dodaj wizytę
  .card-body
    = bootstrap_form_for [ @parishioner, @visit ] do |visit|
      .field
        = visit.date_field :issue, label: "Data wizyty"
      .field
        = visit.check_box :eucharist, label: "Komunia"
      .field
        = visit.check_box :confession, label: "Spowiedź"
      .field
        = visit.check_box :anointing, label: "Namaszczenie"
      .field
        = visit.text_area :notes, label: "Notatki"
      .field
        = visit.collection_select(:minister_id, current_user.ministers, :id, :fullname, {include_blank: 'Wybierz', label: 'Szafarz'}, { class: "selectpicker", data: { live_search: 'true' } })
        = visit.hidden_field :user_id, :value => @current_user.id
      .actions.mt-4
        = visit.submit "Wyślij", class: "btn btn-primary float-right mb-4"
      Aby dopisać wizytę musisz wybrać datę!

app/views/visits/edit.html.haml
= render 'item', visit: @visit

app/views/visits/index.html.haml
.no-print
  %h5 
    Wizyty
    |
    = link_to 'Adresy', places_path
    |
    = link_to 'Parafianie', parishioners_path
    |
    = link_to 'Grupy', characteristics_path
  = search_form_for @q, html: { class: 'form-row' } do |f|
    .form-group.col-auto
      = f.date_field :issue_gteq, class: 'form-control'
    .form-group.col-auto
      = f.date_field :issue_lteq, class: 'form-control'
    .form-group.col-auto
      = f.text_field :parishioner_firstname_cont, placeholder: 'Imię', class: 'form-control'
    .form-group.col-auto
      = f.text_field :parishioner_lastname_cont, placeholder: 'Nazwisko', class: 'form-control'
    .form-group.col-auto
      = f.button "Szukaj", name: nil, class: 'btn btn-icon icon-left btn-primary'
  %b#notice.text-primary= notice
  = will_paginate @visits
%table.table.table-striped.table-bordered.table-hover
  %tbody
    %tr
      %td Data
      %td Osoba i adres
      %td Sakramenty
      %td Szafarz
    - @visits.each do |visit|
      %tr
        %td= link_to visit.issue.strftime("%d-%m-%Y"), edit_visit_path(visit)
        %td
          %b= link_to visit.parishioner.fullname, visit.parishioner, class: 'text-primary'
          %br
          = link_to visit.parishioner.place.full_address, visit.parishioner.place
        %td
          - if visit.eucharist  == true 
            .badge.badge-primary.text-white.mb-2 Komunia
          - if visit.confession  == true 
            .badge.badge-primary.text-white.mb-2 Spowiedź
          - if visit.anointing  == true 
            .badge.badge-primary.text-white.mb-2 Namaszczenie
          %p= visit.notes
        %td= visit.minister.fullname
.no-print
  .mt-4= will_paginate @visits
  

app/views/visits/new.html.haml
%h5 
  = link_to 'Wizyty', visits_path
  | Nowa wizyta
= render 'form', visit: @visit

app/views/visits/show.html.haml
= render 'item', visit: @visit