config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :characteristics
  resources :features
  resources :ministers
  resources :places do
    resources :parishioners
  end
  resources :parishioners do
    resources :visits
  end
  resources :streets
  resources :visits
  root "streets#index"
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
end

app/models/parishioner.rb
class Parishioner < ApplicationRecord
  belongs_to :place
  belongs_to :user
  has_many :visits, dependent: :destroy
  accepts_nested_attributes_for :visits
  has_many :characteristics_parishioners
  has_many :characteristics, through: :characteristics_parishioners, :dependent => :destroy
  default_scope { order(lastname: :asc, firstname: :asc) }
  validates :firstname, :lastname, :birth, :place_id, :presence => true
  def fullname
    "#{firstname} #{lastname}"
  end
  def self.ransackable_associations(auth_object = nil)
    ["characteristics", "characteristics_parishioners", "place", "user", "visits"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["archive", "baptism_date", "baptism_number", "baptism_parish", "birth", "birth_place", "confirmation_date", "confirmation_name", "confirmation_number", "confirmation_witness", "created_at", "death_date", "death_mark", "email", "firstname", "id", "lastname", "notes", "phone", "place_id", "updated_at", "user_id"]
  end
end

app/controllers/parishioners_controller.rb
class ParishionersController < ApplicationController
  before_action :authorize
  before_action :set_parishioner, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.parishioners.includes(:place).ransack(params[:q])
    @parishioners = @q.result.paginate(page: params[:page])
    @stats= @q.result(distinct: true)
  end

  def show
    @visit = current_user.visits.build
    @visit.parishioner_id = @parishioner.id
    @parishioner.visits.build
  end

  def new
  end

  def edit
  end

  def create
    @place = current_user.places.find(params[:place_id])
    @parishioner = @place.parishioners.create(parishioner_params)
    redirect_to @place
  end

  def update
    if @parishioner.update(parishioner_params)
      redirect_to @parishioner, notice: 'Osoba została zaktualizowana.'
    else
      render :edit
    end
  end

  def destroy
    @place = current_user.places.find(params[:place_id])
    @parishioner = @place.parishioners.find(params[:id])
    @parishioner.destroy
    redirect_to place_path(@place), notice: 'Osoba została usunięta.'
  end

  private

    def set_parishioner
      @parishioner = current_user.parishioners.find(params[:id])
    end
    def set_place
      @place= current_user.places.find(params[:place_id])
    end

    def parishioner_params
      params.require(:parishioner).permit(:firstname, :lastname, :birth, :birth_place, :place_id, :phone, :email, :death_mark, :death_date, :baptism_date, :baptism_parish, :baptism_number, :confirmation_name, :confirmation_witness, :confirmation_date, :confirmation_number, :notes, :archive, :user_id, :characteristic_ids=>[], visits_attributes: [:id, :visit_id, :issue, :parishioner_id, :minister_id, :eucharist, :anointing, :confession, :notes, :user_id, :_destroy])
    end
end

app/helpers/parishioners_helper.rb
module ParishionersHelper
end

app/views/parishioners/_form.html.haml
= bootstrap_form_for @parishioner do |f|
  - if @parishioner.errors.any?
    #error_explanation
      %b.text-primary= "#{pluralize(@parishioner.errors.count, "")} do poprawienia:"
  .row
    .col
      = f.text_field :firstname, label: "Imię"
    .col
      = f.text_field :lastname, label: "Nazwisko"
  .row
    .col
      = f.date_field :birth, label: "Data urodzenia", input_html: { 'style' => 'display: inline' }
    .col
      = f.collection_select(:place_id, current_user.places.includes(:street).merge(current_user.streets.order(name: :asc, address: :asc)).all, :id, :full_address, {label: 'Adres zamieszkania'}, { class: "selectpicker", data: { live_search: 'true' } })
  .row
    .col
      = f.text_field :phone, label: "Telefon"
    .col
      = f.text_field :email, label: "Email"
  %button.btn.btn-outline-primary{"aria-controls" => "confirmation-collapse", "aria-expanded" => "false", "data-target" => "#confirmation-collapse", "data-toggle" => "collapse", :type => "button"}
    Dane do bierzmowania
  #confirmation-collapse.collapse
    .field.mt-2
      = f.text_field :birth_place, label: "Miejscowość urodzenia"
    .field
      = f.date_field :baptism_date, label: "Data chrztu"
    .field
      = f.text_field :baptism_parish, label: "Parafia chrztu"
    .field
      = f.text_field :baptism_number, label: "Nr w księdze chrztów"
    .field
      = f.text_field :confirmation_name, label: "Imię do bierzmowania"
    .field
      = f.text_field :confirmation_witness, label: "Świadek bierzmowania"
    .field
      = f.date_field :confirmation_date, label: "Data bierzmowania"
    .field
      = f.text_field :confirmation_number, label: "Nr w księdze bierzmowanych"
  - if parishioner.death_mark == true 
    .field.mt-2
      = f.check_box :death_mark, label: "Osoba zmarła"
    .field
      = f.date_field :death_date, label: "Data śmierci"
  - else
    %button.btn.btn-outline-primary{"aria-controls" => "colllapsedeath", "aria-expanded" => "false", "data-target" => "#colllapsedeath", "data-toggle" => "collapse", :type => "button"}
      Nekrolog
    #colllapsedeath.collapse
      .field.mt-2
        = f.check_box :death_mark, label: "Osoba zmarła"
      .field
        = f.date_field :death_date, label: "Data śmierci"
    %button.btn.btn-outline-primary{"aria-controls" => "characteristic-collapse", "aria-expanded" => "false", "data-target" => "#characteristic-collapse", "data-toggle" => "collapse", :type => "button"}
      Pokaż listę grup
    #characteristic-collapse.collapse 
      .mt-2= f.collection_check_boxes(:characteristic_ids, current_user.characteristics, :id, :name, {label: 'Grupy'})
  %br
  %br
  .field
    = f.text_area :notes, label: "Notatki"
  - if parishioner.death_mark == true
  - else
    .field
      = f.check_box :archive, label: "Archiwum"
  .actions
    = f.submit 'Wyślij', class: "btn btn-primary float-right mb-4"

app/views/parishioners/_item.html.haml
%h5
  = link_to 'Ulice', streets_path
  |
  = link_to 'Adresy', places_path
  |
  = link_to @parishioner.place.street.name, @parishioner.place.street
  |
  = link_to @parishioner.place.address, @parishioner.place
  |
  = @parishioner.archive ? "&#128193;".html_safe : "".html_safe
  = @parishioner.fullname
%p
  - @parishioner.characteristics.each do |characteristic|
    = link_to characteristic.name, characteristic, class: "btn btn-info mb-2 mt-2"
%p
  %b#notice.text-primary= notice
= render 'form', parishioner: @parishioner



%table.table.table-striped.table-bordered.table-hover.mb-4.py-4
  %tbody
    - @parishioner.visits.limit(5).each do |visit|
      %tr
        - unless visit.id.blank?
          %td
            - if visit.issue.present?
              = link_to visit.issue.strftime("%d-%m-%Y"), edit_visit_path(visit)
          %td
            - if visit.eucharist  == true 
              .badge.badge-primary.text-white.mb-2 Komunia
            - if visit.confession  == true 
              .badge.badge-primary.text-white.mb-2 Spowiedź
            - if visit.anointing  == true 
              .badge.badge-primary.text-white.mb-2 Namaszczenie
            %p= visit.notes
          %td
            - if visit.minister.present?
              = visit.minister.fullname
          %td
            - if visit.id.present?
              = link_to "Usuń", parishioner_visit_path(@parishioner, visit.id), title: 'Usuń', class: 'btn btn-sm btn-outline-dark float-right', method: :delete, data: { confirm: 'Czy chcesz wizytę z bazy?', remote: true }

.mt-4= render partial: 'visits/visit'

app/views/parishioners/_parishioner.html.haml
.card.text-white.bg-primary
  .card-header
    Dodaj mieszkańca
  .card-body
    = bootstrap_form_for [ @place, @parishioner ] do |parishioner|
      .row
        .col
          = parishioner.text_field :firstname, label: "Imię"
        .col
          = parishioner.text_field :lastname, label: "Nazwisko"
      .row
        .col
          = parishioner.date_field :birth, label: "Data urodzenia", input_html: { 'style' => 'display: inline' }
          = parishioner.hidden_field :user_id, :value => @current_user.id
      .actions
        = parishioner.submit 'Dodaj', class: "btn btn-primary float-right mb-4"
        Wszystkie pola musza być wypełnione!

app/views/parishioners/edit.html.haml
= render 'item', parishioner: @parishioner

app/views/parishioners/index.html.haml
%h5 
  = link_to 'Ulice', streets_path
  |
  = link_to 'Adresy', places_path
  |
  Parafianie
  |
  = link_to 'Grupy', characteristics_path
= search_form_for @q, html: { class: 'form-row' } do |f|
  .form-group.col-auto
    = f.collection_select :place_street_id_eq, current_user.streets.order(:name), :id, :name, { include_blank: 'Wszystkie ulice' }, { class: "selectpicker", data: { live_search: 'true' } }
  .form-group.col-auto
    = f.text_field :place_address_cont, placeholder: 'Nr domu lub mieszkania', class: 'form-control'
  .form-group.col-auto
    = f.text_field :firstname_cont, placeholder: 'Imię', class: 'form-control'
  .form-group.col-auto
    = f.text_field :lastname_cont, placeholder: 'Nazwisko', class: 'form-control'
  .form-group.col-auto
    = f.button "Szukaj", name: nil, class: 'btn btn-icon icon-left btn-primary'
Znaleziono 
%b= @stats.count - @stats.where(archive: 1).count
aktywnych kart parafian i
%b= @stats.where(archive: 1).count
archiwalnych.
%br
%br
%b#notice.text-primary= notice
= will_paginate @parishioners
%table.table.table-striped.table-bordered.table-hover.mb-4.py-4
  %tbody
    - @parishioners.each do |parishioner|
      %tr
        %td!
          - if parishioner.death_mark == true 
            = parishioner.death_mark ? "✝️".html_safe : " ".html_safe
          - else
            = parishioner.archive ? "📁".html_safe : " ".html_safe
          %b= link_to parishioner.fullname, parishioner, class: 'text-primary'
          %br
          = link_to parishioner.place.full_address, parishioner.place
        %td
          - if parishioner.death_mark == true 
            - if parishioner.birth.present?
              = parishioner.birth.strftime("ur. %d-%m-%Y")
            
            - if parishioner.death_date.present?
              = parishioner.death_date.strftime("zm. %d-%m-%Y")
              w wieku
              %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor - ((Time.zone.now - parishioner.death_date.to_time) / 1.year.seconds).floor
              lat
              
          - else
            - if parishioner.birth.present?
              lat 
              %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor
              = parishioner.birth.strftime("ur. %d-%m-%Y")
            
          %i.text-primary= parishioner.notes
.mt-4= will_paginate @parishioners

app/views/parishioners/new.html.haml
%h5 
  = link_to 'Adresy', parishioners_path
  | Nowy adres
= render 'form', parishioner: @parishioner

app/views/parishioners/show.html.haml
= render 'item', parishioner: @parishioner