config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :characteristics
  resources :features
  resources :ministers
  resources :places do
    resources :parishioners
  end
  resources :parishioners do
    resources :visits
  end
  resources :streets
  resources :visits
  root "streets#index"
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :street
  belongs_to :user
  before_save :change_numbers
  has_many :parishioners, dependent: :destroy
  accepts_nested_attributes_for :parishioners
  has_many :features_places
  has_many :features, through: :features_places, :dependent => :destroy
  validates :address, :street_id, :presence => true
  default_scope { joins(:street).merge(Street.order(name: :asc, address: :asc)).all }
  def next
    Place.where("street_id = ? AND address > ?", self.street.id, address).first || Place.where("street_id = ?", self.street.id).first
  end
  def prev
    Place.where("street_id = ? AND address < ?", self.street.id, address).last || Place.where("street_id = ?", self.street.id).last
  end
  def full_address
    "#{street.name} #{address}"
  end
  def self.ransackable_attributes(auth_object = nil)
    ["address", "archive", "created_at", "id", "notes", "street_id", "updated_at", "user_id"]
  end
  def change_numbers
    address.gsub!(/\b([0-9])\b/, '00\1')
    address.gsub!(/\b([0-9]{2})\b/, '0\1')
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authorize
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.places.includes(:street).ransack(params[:q])
    @places = @q.result.paginate(page: params[:page])
    @streets = current_user.streets
    @features = current_user.features
    @stats= @q.result(distinct: true)
  end

  def show
    @parishioner = current_user.parishioners.build
    @parishioner.place_id = @place.id
    @place.parishioners.build
  end

  def new
    @place = current_user.places.build
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)

    if @place.save
      redirect_to @place, notice: 'Adres został dodany.'
    else
      render :new
    end
  end

  def update
    if @place.update(place_params)
      redirect_to @place, notice: 'Adres został zaktualizowany.'
    else
      render :edit
    end
  end

  def destroy
    @place.destroy
    redirect_to places_url, notice: 'Adres i powiązane z nim dane zostały usuniete.'
  end

  private

    def set_place
      @place = current_user.places.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:street_id, :address, :notes, :archive, :feature_ids=>[], parishioners_attributes: [:id, :place_id, :firstname, :lastname, :birth, :user_id, :_destroy, :characteristic_ids=>[]])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.haml
= bootstrap_form_with(model: place) do |form|
  - if place.errors.any?
    #error_explanation
      %b.text-primary
        = pluralize(place.errors.count, "")
        do poprawienia!
  .row
    .col
      = form.collection_select(:street_id, current_user.streets, :id, :name, {label: 'Ulica', include_blank: 'Wszystkie ulice' }, { class: "selectpicker", data: { live_search: 'true' } })
    .col
      = form.text_field :address, label: "Nr domu/mieszkania"
  .field 
    = form.collection_check_boxes(:feature_ids, current_user.features, :id, :name, {label: 'Tagi adresu'})
  .field
    = form.text_area :notes, label: "Notatki"
  .field
    = form.check_box :archive, label: "Archiwum"
  .actions.mt-4
    = form.submit "Wyślij", class: "btn btn-primary float-right mb-4"
%br
%br
%br

app/views/places/_item.html.haml
= link_to "Usuń", @place, title: 'Usuń', class: 'btn btn-dark float-right', method: :delete, data: { confirm: 'Czy chcesz usunąć adres wraz z wszystkimi danymi z nim powiązanymi?', remote: true }
%h5
  = link_to 'Ulice', streets_path
  |
  = link_to 'Adresy', places_path
  |
  = link_to @place.street.name, @place.street
  |
  = @place.archive ? "&#128193;".html_safe : "".html_safe
  = @place.address
= link_to '&larr; poprzedni'.html_safe, @place.prev, class: "btn btn-outline-primary mr-2 mb-2"
= link_to 'następny &rarr;'.html_safe, @place.next, class: "btn btn-outline-primary mb-2"
%p
  - @place.features.each do |feature|
    = link_to feature.name, feature, class: "badge badge-info mb-2 mt-2"
%p
  %b#notice.text-primary= notice
= render 'form', place: @place

%table.table.table-striped.table-bordered.table-hover.mb-4.py-4
  %tbody
    - @place.parishioners.reorder(death_mark: :asc, archive: :asc, birth: :asc).each do |parishioner|
      %tr
        %td
          - if parishioner.death_mark == true 
            = parishioner.death_mark ? "✝️".html_safe : " ".html_safe
          - else
            = parishioner.archive ? "📁".html_safe : " ".html_safe
          %b= link_to parishioner.fullname, parishioner, class: 'text-primary'
        %td
          - if parishioner.death_mark == true 
            - if parishioner.birth.present?
              = parishioner.birth.strftime("ur. %d-%m-%Y")
            
            - if parishioner.death_date.present?
              = parishioner.death_date.strftime("zm. %d-%m-%Y")
              w wieku
              %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor - ((Time.zone.now - parishioner.death_date.to_time) / 1.year.seconds).floor
              lat
              
          - else
            - if parishioner.birth.present?
              lat 
              %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor
              = parishioner.birth.strftime("ur. %d-%m-%Y")
              
          %i.text-primary= parishioner.notes
          - parishioner.characteristics.each do |characteristic|
            = characteristic.name
          = link_to "Usuń", place_parishioner_path(@place, parishioner.id), title: 'Usuń', class: 'btn btn-sm btn-outline-dark float-right', method: :delete, data: { confirm: 'Czy chcesz usunąć osobę z bazy?', remote: true }

= render partial: 'parishioners/parishioner'

app/views/places/edit.html.haml
= render 'item', place: @place

app/views/places/index.html.haml
= link_to '+ Nowy', new_place_path, class: "btn btn-primary float-right mb-2"
%h5 
  = link_to 'Ulice', streets_path
  |
  Adresy
  |
  = link_to 'Parafianie', parishioners_path
  |
  = link_to 'Grupy', characteristics_path
= search_form_for @q, html: { class: 'form-row' } do |f|
  .form-group.col-auto
    = f.collection_select :street_id_eq, current_user.streets.order(:name), :id, :name, { include_blank: 'Wszystkie ulice' }, { class: "selectpicker", data: { live_search: 'true' } }
  .form-group.col-auto
    = f.text_field :address_cont, placeholder: 'Nr domu lub mieszkania', class: 'form-control'
  .form-group.auto
    = f.button "Szukaj", name: nil, class: 'btn btn-icon icon-left btn-primary'
%b#notice.text-primary= notice
Znaleziono 
%b= @stats.where(archive: 0).count
aktywnych adresów i
%b= @stats.where(archive: 1).count
archiwalnych.
%br
%br
= will_paginate @places
%table.table.table-striped.table-bordered.table-hover.mb-4.py-4
  %thead
    %tr
      %th Adres
      %th Notatki
  %tbody
    - @places.each do |place|
      %tr
        %td!
          = place.archive ? "📁".html_safe : " ".html_safe
          = link_to place.full_address, place
          %p
            - place.features.each do |feature|
              = link_to feature.name, feature, class: "badge badge-info mb-2 mt-2"
        %td
          = place.notes
          %ul
            - place.parishioners.reorder(death_mark: :asc, archive: :asc, birth: :asc).each do |parishioner|
              %li
                - if parishioner.death_mark == true 
                  = parishioner.death_mark ? "✝️".html_safe : " ".html_safe
                - else
                  = parishioner.archive ? "📁".html_safe : " ".html_safe
                %b= link_to parishioner.fullname, parishioner, class: 'text-primary'
                
                - if parishioner.death_mark == true 
                  - if parishioner.birth.present?
                    = parishioner.birth.strftime("ur. %d-%m-%Y")
                  
                  - if parishioner.death_date.present?
                    = parishioner.death_date.strftime("zm. %d-%m-%Y")
                    w wieku
                    %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor - ((Time.zone.now - parishioner.death_date.to_time) / 1.year.seconds).floor
                    lat
                    
                - else
                  - if parishioner.birth.present?
                    lat 
                    %ins= ((Time.zone.now - parishioner.birth.to_time) / 1.year.seconds).floor
                    = parishioner.birth.strftime("ur. %d-%m-%Y")
                    
                    %i.text-primary= parishioner.notes
.mt-4= will_paginate @places

app/views/places/new.html.haml
%h5 
  = link_to 'Adresy', places_path
  | Nowy adres
= render 'form', place: @place

app/views/places/show.html.haml
= render 'item', place: @place